project:
  type: website

website:
  title: "Collection of slides for teaching and other presentations"
  navbar:
    tools:
      - icon: github
        text: Source Code
        href: https://github.com/mitmat/slides-v2

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

